<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE resultset[
<!ELEMENT resultset (summary,results)>
<!ELEMENT summary (status,sessionID,NumOfErrors,NumOfLikelyProblems,NumOfPotentialProblems,guidelines)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT sessionID (#PCDATA)>
<!ELEMENT NumOfErrors (#PCDATA)>
<!ELEMENT NumOfLikelyProblems (#PCDATA)>
<!ELEMENT NumOfPotentialProblems (#PCDATA)>
<!ELEMENT guidelines (guideline)*>
<!ELEMENT guideline (#PCDATA)>
<!ELEMENT results (result)*>
<!ELEMENT result (resultType,lineNum,columnNum,errorMsg,errorSourceCode,repair*,sequenceID*,decisionPass*,decisionFail*,decisionMade*,decisionMadeDate*)>
<!ELEMENT resultType (#PCDATA)>
<!ELEMENT lineNum (#PCDATA)>
<!ELEMENT columnNum (#PCDATA)>
<!ELEMENT errorMsg (#PCDATA)>
<!ELEMENT errorSourceCode (#PCDATA)>
<!ELEMENT repair (#PCDATA)>
<!ELEMENT sequenceID (#PCDATA)>
<!ELEMENT decisionPass (#PCDATA)>
<!ELEMENT decisionFail (#PCDATA)>
<!ELEMENT decisionMade (#PCDATA)>
<!ELEMENT decisionMadeDate (#PCDATA)>
<!ENTITY lt "&#38;#60;">
<!ENTITY gt "&#62;">
<!ENTITY amp "&#38;#38;">
<!ENTITY apos "&#39;">
<!ENTITY quot "&#34;">
]>
<resultset>
  <summary>
    <status>CONDITIONAL PASS</status>
    <sessionID>753f9daa3464ad474fbec5ef8b84a74f636622f1</sessionID>
    <NumOfErrors>0</NumOfErrors>
    <NumOfLikelyProblems>0</NumOfLikelyProblems>
    <NumOfPotentialProblems>198</NumOfPotentialProblems>

    <guidelines>
      <guideline>WCAG 2.0 (Level AA)</guideline>

    </guidelines>
  </summary>

  <results>
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>6</lineNum>
      <columnNum>2</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=54&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=54'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;&lt;code&gt;title&lt;/code&gt; might not describe the document.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;title&gt;IDI Web Accessibility Checker : Web Accessibility Checker&lt;/title&gt;</errorSourceCode>
        
        <sequenceID>6_2_54</sequenceID>
        <decisionPass>&lt;code&gt;title&lt;/code&gt; describes the document.</decisionPass>
        <decisionFail>&lt;code&gt;title&lt;/code&gt; does not describe the document.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>18</lineNum>
      <columnNum>2</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=87&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=87'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;&lt;code&gt;script&lt;/code&gt; may cause screen flicker.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;script src=&quot;http://achecker.ca/jscripts/lib/jquery.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;</errorSourceCode>
        
        <sequenceID>18_2_87</sequenceID>
        <decisionPass>&lt;code&gt;script&lt;/code&gt; does not cause screen flicker.</decisionPass>
        <decisionFail>&lt;code&gt;script&lt;/code&gt; causes screen flicker.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>18</lineNum>
      <columnNum>2</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=86&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=86'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;&lt;code&gt;script&lt;/code&gt; may use color alone.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;script src=&quot;http://achecker.ca/jscripts/lib/jquery.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;</errorSourceCode>
        
        <sequenceID>18_2_86</sequenceID>
        <decisionPass>&lt;code&gt;script&lt;/code&gt; does not use color alone.</decisionPass>
        <decisionFail>&lt;code&gt;script&lt;/code&gt; uses color alone.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>18</lineNum>
      <columnNum>2</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=89&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=89'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;&lt;code&gt;script&lt;/code&gt; user interface may not be accessible.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;script src=&quot;http://achecker.ca/jscripts/lib/jquery.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;</errorSourceCode>
        
        <sequenceID>18_2_89</sequenceID>
        <decisionPass>&lt;code&gt;script&lt;/code&gt; user interface is accessible.</decisionPass>
        <decisionFail>&lt;code&gt;script&lt;/code&gt; user interface is not accessible.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>19</lineNum>
      <columnNum>2</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=87&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=87'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;&lt;code&gt;script&lt;/code&gt; may cause screen flicker.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;script src=&quot;http://achecker.ca/jscripts/lib/jquery-URLEncode.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;</errorSourceCode>
        
        <sequenceID>19_2_87</sequenceID>
        <decisionPass>&lt;code&gt;script&lt;/code&gt; does not cause screen flicker.</decisionPass>
        <decisionFail>&lt;code&gt;script&lt;/code&gt; causes screen flicker.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>19</lineNum>
      <columnNum>2</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=86&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=86'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;&lt;code&gt;script&lt;/code&gt; may use color alone.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;script src=&quot;http://achecker.ca/jscripts/lib/jquery-URLEncode.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;</errorSourceCode>
        
        <sequenceID>19_2_86</sequenceID>
        <decisionPass>&lt;code&gt;script&lt;/code&gt; does not use color alone.</decisionPass>
        <decisionFail>&lt;code&gt;script&lt;/code&gt; uses color alone.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>19</lineNum>
      <columnNum>2</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=89&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=89'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;&lt;code&gt;script&lt;/code&gt; user interface may not be accessible.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;script src=&quot;http://achecker.ca/jscripts/lib/jquery-URLEncode.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;</errorSourceCode>
        
        <sequenceID>19_2_89</sequenceID>
        <decisionPass>&lt;code&gt;script&lt;/code&gt; user interface is accessible.</decisionPass>
        <decisionFail>&lt;code&gt;script&lt;/code&gt; user interface is not accessible.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>20</lineNum>
      <columnNum>2</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=87&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=87'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;&lt;code&gt;script&lt;/code&gt; may cause screen flicker.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;script src=&quot;http://achecker.ca/jscripts/AChecker.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;</errorSourceCode>
        
        <sequenceID>20_2_87</sequenceID>
        <decisionPass>&lt;code&gt;script&lt;/code&gt; does not cause screen flicker.</decisionPass>
        <decisionFail>&lt;code&gt;script&lt;/code&gt; causes screen flicker.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>20</lineNum>
      <columnNum>2</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=86&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=86'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;&lt;code&gt;script&lt;/code&gt; may use color alone.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;script src=&quot;http://achecker.ca/jscripts/AChecker.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;</errorSourceCode>
        
        <sequenceID>20_2_86</sequenceID>
        <decisionPass>&lt;code&gt;script&lt;/code&gt; does not use color alone.</decisionPass>
        <decisionFail>&lt;code&gt;script&lt;/code&gt; uses color alone.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>20</lineNum>
      <columnNum>2</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=89&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=89'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;&lt;code&gt;script&lt;/code&gt; user interface may not be accessible.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;script src=&quot;http://achecker.ca/jscripts/AChecker.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;</errorSourceCode>
        
        <sequenceID>20_2_89</sequenceID>
        <decisionPass>&lt;code&gt;script&lt;/code&gt; user interface is accessible.</decisionPass>
        <decisionFail>&lt;code&gt;script&lt;/code&gt; user interface is not accessible.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>22</lineNum>
      <columnNum>1</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=87&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=87'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;&lt;code&gt;script&lt;/code&gt; may cause screen flicker.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;script src=&quot;http://achecker.ca/checker/js/checker.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;</errorSourceCode>
        
        <sequenceID>22_1_87</sequenceID>
        <decisionPass>&lt;code&gt;script&lt;/code&gt; does not cause screen flicker.</decisionPass>
        <decisionFail>&lt;code&gt;script&lt;/code&gt; causes screen flicker.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>22</lineNum>
      <columnNum>1</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=86&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=86'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;&lt;code&gt;script&lt;/code&gt; may use color alone.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;script src=&quot;http://achecker.ca/checker/js/checker.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;</errorSourceCode>
        
        <sequenceID>22_1_86</sequenceID>
        <decisionPass>&lt;code&gt;script&lt;/code&gt; does not use color alone.</decisionPass>
        <decisionFail>&lt;code&gt;script&lt;/code&gt; uses color alone.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>22</lineNum>
      <columnNum>1</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=89&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=89'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;&lt;code&gt;script&lt;/code&gt; user interface may not be accessible.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;script src=&quot;http://achecker.ca/checker/js/checker.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;</errorSourceCode>
        
        <sequenceID>22_1_89</sequenceID>
        <decisionPass>&lt;code&gt;script&lt;/code&gt; user interface is accessible.</decisionPass>
        <decisionFail>&lt;code&gt;script&lt;/code&gt; user interface is not accessible.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>23</lineNum>
      <columnNum>1</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=87&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=87'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;&lt;code&gt;script&lt;/code&gt; may cause screen flicker.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;script type=&quot;text/javascript&quot;&gt;

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-17057267-4 ...</errorSourceCode>
        
        <sequenceID>23_1_87</sequenceID>
        <decisionPass>&lt;code&gt;script&lt;/code&gt; does not cause screen flicker.</decisionPass>
        <decisionFail>&lt;code&gt;script&lt;/code&gt; causes screen flicker.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>23</lineNum>
      <columnNum>1</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=86&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=86'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;&lt;code&gt;script&lt;/code&gt; may use color alone.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;script type=&quot;text/javascript&quot;&gt;

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-17057267-4 ...</errorSourceCode>
        
        <sequenceID>23_1_86</sequenceID>
        <decisionPass>&lt;code&gt;script&lt;/code&gt; does not use color alone.</decisionPass>
        <decisionFail>&lt;code&gt;script&lt;/code&gt; uses color alone.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>23</lineNum>
      <columnNum>1</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=89&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=89'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;&lt;code&gt;script&lt;/code&gt; user interface may not be accessible.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;script type=&quot;text/javascript&quot;&gt;

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-17057267-4 ...</errorSourceCode>
        
        <sequenceID>23_1_89</sequenceID>
        <decisionPass>&lt;code&gt;script&lt;/code&gt; user interface is accessible.</decisionPass>
        <decisionFail>&lt;code&gt;script&lt;/code&gt; user interface is not accessible.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>38</lineNum>
      <columnNum>1</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=250&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=250'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;Text may refer to items by shape, size, or relative position alone.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;body onload=&quot;AChecker.input.initialize('by_uri', 'by_guideline');&quot;&gt;

&lt;div id=&quot;liquid-round&quot;&gt;&lt;div cl ...</errorSourceCode>
        
        <sequenceID>38_1_250</sequenceID>
        <decisionPass>There are no references to items in the document by shape, size, or relative position alone.</decisionPass>
        <decisionFail>There are references to items in the document by shape, size, or relative position alone.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>38</lineNum>
      <columnNum>1</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=131&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=131'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;Long quotations may not be marked using the &lt;code&gt;blockquote&lt;/code&gt; element.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;body onload=&quot;AChecker.input.initialize('by_uri', 'by_guideline');&quot;&gt;

&lt;div id=&quot;liquid-round&quot;&gt;&lt;div cl ...</errorSourceCode>
        
        <sequenceID>38_1_131</sequenceID>
        <decisionPass>All long quotations have been marked with the &lt;code&gt;blockquote&lt;/code&gt; element.</decisionPass>
        <decisionFail>All long quotations are not marked with the &lt;code&gt;blockquote&lt;/code&gt; element.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>38</lineNum>
      <columnNum>1</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=270&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=270'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;Unicode right-to-left marks or left-to-right marks may be required.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;body onload=&quot;AChecker.input.initialize('by_uri', 'by_guideline');&quot;&gt;

&lt;div id=&quot;liquid-round&quot;&gt;&lt;div cl ...</errorSourceCode>
        
        <sequenceID>38_1_270</sequenceID>
        <decisionPass>Unicode right-to-left marks or left-to-right marks are used whenever the HTML bidirectional algorithm produces undesirable results.</decisionPass>
        <decisionFail>Unicode right-to-left marks or left-to-right marks are not used whenever the HTML bidirectional algorithm produces undesirable results.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>38</lineNum>
      <columnNum>1</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=262&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=262'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;Groups of links with a related purpose are not marked.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;body onload=&quot;AChecker.input.initialize('by_uri', 'by_guideline');&quot;&gt;

&lt;div id=&quot;liquid-round&quot;&gt;&lt;div cl ...</errorSourceCode>
        
        <sequenceID>38_1_262</sequenceID>
        <decisionPass>All groups of links with a related purpose are marked.</decisionPass>
        <decisionFail>All groups of links with a related purpose are not marked.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>38</lineNum>
      <columnNum>1</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=276&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=276'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;Repeated components may not appear in the same relative order each time they appear.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;body onload=&quot;AChecker.input.initialize('by_uri', 'by_guideline');&quot;&gt;

&lt;div id=&quot;liquid-round&quot;&gt;&lt;div cl ...</errorSourceCode>
        
        <sequenceID>38_1_276</sequenceID>
        <decisionPass>Repeated components appear in the same relative order on this page.</decisionPass>
        <decisionFail>Repeated components do not appear in the same relative order on this page.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>38</lineNum>
      <columnNum>1</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=275&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=275'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;Loading web page may cause new window to open.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;body onload=&quot;AChecker.input.initialize('by_uri', 'by_guideline');&quot;&gt;

&lt;div id=&quot;liquid-round&quot;&gt;&lt;div cl ...</errorSourceCode>
        
        <sequenceID>38_1_275</sequenceID>
        <decisionPass>Loading the page does not cause a new window to open.</decisionPass>
        <decisionFail>Loading the page causes a new window to open.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>38</lineNum>
      <columnNum>1</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=184&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=184'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;Site missing site map.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;body onload=&quot;AChecker.input.initialize('by_uri', 'by_guideline');&quot;&gt;

&lt;div id=&quot;liquid-round&quot;&gt;&lt;div cl ...</errorSourceCode>
        
        <sequenceID>38_1_184</sequenceID>
        <decisionPass>Page is not part of a collection that requires a site map.</decisionPass>
        <decisionFail>Page is part of a collection that requires a site map.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>38</lineNum>
      <columnNum>1</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=248&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=248'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;Visual lists may not be properly marked.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;body onload=&quot;AChecker.input.initialize('by_uri', 'by_guideline');&quot;&gt;

&lt;div id=&quot;liquid-round&quot;&gt;&lt;div cl ...</errorSourceCode>
        
        <sequenceID>38_1_248</sequenceID>
        <decisionPass>All visual lists contain proper markup.</decisionPass>
        <decisionFail>Not all visual lists contain proper markup.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>38</lineNum>
      <columnNum>1</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=28&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=28'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;Document may be missing a &quot;skip to content&quot; link.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;body onload=&quot;AChecker.input.initialize('by_uri', 'by_guideline');&quot;&gt;

&lt;div id=&quot;liquid-round&quot;&gt;&lt;div cl ...</errorSourceCode>
        
        <sequenceID>38_1_28</sequenceID>
        <decisionPass>Document contians a &quot;skip to content&quot; link or does not require it.</decisionPass>
        <decisionFail>Document does not contain a &quot;skip to content&quot; link and requires it.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>38</lineNum>
      <columnNum>1</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=241&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=241'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;Tabular information may be missing table markup.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;body onload=&quot;AChecker.input.initialize('by_uri', 'by_guideline');&quot;&gt;

&lt;div id=&quot;liquid-round&quot;&gt;&lt;div cl ...</errorSourceCode>
        
        <sequenceID>38_1_241</sequenceID>
        <decisionPass>Table markup is used for all tabular information.</decisionPass>
        <decisionFail>Table markup is not used for all tabular information.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>38</lineNum>
      <columnNum>1</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=271&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=271'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;&lt;code&gt;dir&lt;/code&gt; attribute may be required to identify changes in text direction.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;body onload=&quot;AChecker.input.initialize('by_uri', 'by_guideline');&quot;&gt;

&lt;div id=&quot;liquid-round&quot;&gt;&lt;div cl ...</errorSourceCode>
        
        <sequenceID>38_1_271</sequenceID>
        <decisionPass>All changes in text direction are marked using the &lt;code&gt;dir&lt;/code&gt; attribute.</decisionPass>
        <decisionFail>All changes in text direction are not marked using the &lt;code&gt;dir&lt;/code&gt; attribute.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>38</lineNum>
      <columnNum>1</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=110&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=110'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;Words or phrases that are not in the document's primary language may not be identified.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;body onload=&quot;AChecker.input.initialize('by_uri', 'by_guideline');&quot;&gt;

&lt;div id=&quot;liquid-round&quot;&gt;&lt;div cl ...</errorSourceCode>
        
        <sequenceID>38_1_110</sequenceID>
        <decisionPass>All words outside the primary language are identified.</decisionPass>
        <decisionFail>Words outside the primary language are not identified.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>43</lineNum>
      <columnNum>4</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=197&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=197'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;Anchor text may not identify the link destination.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;a href=&quot;http://www.atutor.ca/achecker/&quot;&gt;&lt;img src=&quot;http://achecker.ca/themes/default/images/checker_ ...</errorSourceCode>
        
        <sequenceID>43_4_197</sequenceID>
        <decisionPass>Anchor has text that identifies the link destination.</decisionPass>
        <decisionFail>Anchor does not have text that identifies the link destination.</decisionFail>

    </result> 
    <result>
      <resultType>Potential Problem</resultType>
      <lineNum>43</lineNum>
      <columnNum>4</columnNum>
      <errorMsg>&lt;a href=&quot;http://achecker.ca/checker/suggestion.php?id=19&quot;
               onclick=&quot;AChecker.popup('http://achecker.ca/checker/suggestion.php?id=19'); return false;&quot; 
               title=&quot;Suggest improvements on this error message&quot; target=&quot;_new&quot;&gt;Link text may not be meaningful.&lt;/a&gt;
      </errorMsg>
      <errorSourceCode>&lt;a href=&quot;http://www.atutor.ca/achecker/&quot;&gt;&lt;img src=&quot;http://achecker.ca/themes/default/images/checker_ ...</errorSourceCode>
        
        <sequenceID>43_4_19</sequenceID>